// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAId86Lj-sxMAarARIKSUIWZLiyF4aaxfQ',
    appId: '1:579925775733:web:6b79385d705ff4a7f7ef3c',
    messagingSenderId: '579925775733',
    projectId: 'tasker-backend-82541',
    authDomain: 'tasker-backend-82541.firebaseapp.com',
    storageBucket: 'tasker-backend-82541.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDLozcmJ-H43EnjoL0p-r-753twI6pmRk',
    appId: '1:579925775733:android:f90e2c2043455f2bf7ef3c',
    messagingSenderId: '579925775733',
    projectId: 'tasker-backend-82541',
    storageBucket: 'tasker-backend-82541.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGHY8qzFmKypo3Gj2Tz-YeZD0Uzezox3I',
    appId: '1:579925775733:ios:0c8a2e4e8deba577f7ef3c',
    messagingSenderId: '579925775733',
    projectId: 'tasker-backend-82541',
    storageBucket: 'tasker-backend-82541.firebasestorage.app',
    iosBundleId: 'com.example.tasker',
  );
}
